/**
 * Generated by `npm run images:build`. Do not edit manually.
 *
 * Local, committed assets — the application makes no request to any external
 * image host. Each entry carries both crops and an inline blur placeholder.
 *
 * The data itself lives in `recipe-images.generated.json`; this module only
 * adds types. The build-time assertion reads the JSON directly, so a formatter
 * changing quote style here cannot silently disable the check.
 */
import generated from './recipe-images.generated.json';

export interface RecipeImageSet {
  /** 16:9 landscape, for the detail hero and the featured card. */
  image: string;
  /** 1:1 square, for grid cards. Cropped from the source, never letterboxed. */
  imageSquare: string;
  /** 20px WebP data URI, inlined so the reserved box is never blank. */
  blurDataURL: string;
}

export const GENERATED_RECIPE_IMAGES: Record<string, RecipeImageSet> = generated;
